services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ./server:/app

  # CLIENTS
  client_one:
    build:
      context: ./client_one
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ./client_one:/app
    depends_on:
      - server

  client_two:
    build:
      context: ./client_two
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ./client_two:/app
    depends_on:
      - server