services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
    volumes:
      - ./server:/app

  # CLIENTS
  client_one:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    volumes:
      - ./d_data/client_one:/app/data
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    depends_on:
      - server

  client_two:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ./d_data/client_two:/app/data
    runtime: nvidia 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    depends_on:
      - server